// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/infobloxopen/protoc-gen-atlas-validate/options/atlas_validate.proto

/*
Package options is a generated protocol buffer package.

It is generated from these files:
	github.com/infobloxopen/protoc-gen-atlas-validate/options/atlas_validate.proto

It has these top-level messages:
	AtlasValidateFileOption
	AtlasValidateMethodOption
	AtlasValidateServiceOption
	AtlasValidateFieldOption
*/
package options

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type AtlasValidateFieldOption_Operation int32

const (
	// Field allow only on create operation
	AtlasValidateFieldOption_create AtlasValidateFieldOption_Operation = 0
	// Field allow only on patch operation
	AtlasValidateFieldOption_patch AtlasValidateFieldOption_Operation = 1
	// Field allow only on replace operation
	AtlasValidateFieldOption_replace AtlasValidateFieldOption_Operation = 2
)

var AtlasValidateFieldOption_Operation_name = map[int32]string{
	0: "create",
	1: "patch",
	2: "replace",
}
var AtlasValidateFieldOption_Operation_value = map[string]int32{
	"create":  0,
	"patch":   1,
	"replace": 2,
}

func (x AtlasValidateFieldOption_Operation) String() string {
	return proto.EnumName(AtlasValidateFieldOption_Operation_name, int32(x))
}
func (AtlasValidateFieldOption_Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorAtlasValidate, []int{3, 0}
}

type AtlasValidateFileOption struct {
	AllowUnknownFields bool `protobuf:"varint,1,opt,name=allow_unknown_fields,json=allowUnknownFields,proto3" json:"allow_unknown_fields,omitempty"`
}

func (m *AtlasValidateFileOption) Reset()         { *m = AtlasValidateFileOption{} }
func (m *AtlasValidateFileOption) String() string { return proto.CompactTextString(m) }
func (*AtlasValidateFileOption) ProtoMessage()    {}
func (*AtlasValidateFileOption) Descriptor() ([]byte, []int) {
	return fileDescriptorAtlasValidate, []int{0}
}

func (m *AtlasValidateFileOption) GetAllowUnknownFields() bool {
	if m != nil {
		return m.AllowUnknownFields
	}
	return false
}

type AtlasValidateMethodOption struct {
	AllowUnknownFields bool `protobuf:"varint,1,opt,name=allow_unknown_fields,json=allowUnknownFields,proto3" json:"allow_unknown_fields,omitempty"`
}

func (m *AtlasValidateMethodOption) Reset()         { *m = AtlasValidateMethodOption{} }
func (m *AtlasValidateMethodOption) String() string { return proto.CompactTextString(m) }
func (*AtlasValidateMethodOption) ProtoMessage()    {}
func (*AtlasValidateMethodOption) Descriptor() ([]byte, []int) {
	return fileDescriptorAtlasValidate, []int{1}
}

func (m *AtlasValidateMethodOption) GetAllowUnknownFields() bool {
	if m != nil {
		return m.AllowUnknownFields
	}
	return false
}

type AtlasValidateServiceOption struct {
	AllowUnknownFields bool `protobuf:"varint,1,opt,name=allow_unknown_fields,json=allowUnknownFields,proto3" json:"allow_unknown_fields,omitempty"`
}

func (m *AtlasValidateServiceOption) Reset()         { *m = AtlasValidateServiceOption{} }
func (m *AtlasValidateServiceOption) String() string { return proto.CompactTextString(m) }
func (*AtlasValidateServiceOption) ProtoMessage()    {}
func (*AtlasValidateServiceOption) Descriptor() ([]byte, []int) {
	return fileDescriptorAtlasValidate, []int{2}
}

func (m *AtlasValidateServiceOption) GetAllowUnknownFields() bool {
	if m != nil {
		return m.AllowUnknownFields
	}
	return false
}

type AtlasValidateFieldOption struct {
	Deny     []AtlasValidateFieldOption_Operation `protobuf:"varint,1,rep,packed,name=deny,enum=atlas_validate.AtlasValidateFieldOption_Operation" json:"deny,omitempty"`
	Required []AtlasValidateFieldOption_Operation `protobuf:"varint,2,rep,packed,name=required,enum=atlas_validate.AtlasValidateFieldOption_Operation" json:"required,omitempty"`
}

func (m *AtlasValidateFieldOption) Reset()         { *m = AtlasValidateFieldOption{} }
func (m *AtlasValidateFieldOption) String() string { return proto.CompactTextString(m) }
func (*AtlasValidateFieldOption) ProtoMessage()    {}
func (*AtlasValidateFieldOption) Descriptor() ([]byte, []int) {
	return fileDescriptorAtlasValidate, []int{3}
}

func (m *AtlasValidateFieldOption) GetDeny() []AtlasValidateFieldOption_Operation {
	if m != nil {
		return m.Deny
	}
	return nil
}

func (m *AtlasValidateFieldOption) GetRequired() []AtlasValidateFieldOption_Operation {
	if m != nil {
		return m.Required
	}
	return nil
}

var E_File = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*AtlasValidateFileOption)(nil),
	Field:         52219,
	Name:          "atlas_validate.file",
	Tag:           "bytes,52219,opt,name=file",
	Filename:      "github.com/infobloxopen/protoc-gen-atlas-validate/options/atlas_validate.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*AtlasValidateMethodOption)(nil),
	Field:         52219,
	Name:          "atlas_validate.method",
	Tag:           "bytes,52219,opt,name=method",
	Filename:      "github.com/infobloxopen/protoc-gen-atlas-validate/options/atlas_validate.proto",
}

var E_Service = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*AtlasValidateServiceOption)(nil),
	Field:         52219,
	Name:          "atlas_validate.service",
	Tag:           "bytes,52219,opt,name=service",
	Filename:      "github.com/infobloxopen/protoc-gen-atlas-validate/options/atlas_validate.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*AtlasValidateFieldOption)(nil),
	Field:         52219,
	Name:          "atlas_validate.field",
	Tag:           "bytes,52219,opt,name=field",
	Filename:      "github.com/infobloxopen/protoc-gen-atlas-validate/options/atlas_validate.proto",
}

func init() {
	proto.RegisterType((*AtlasValidateFileOption)(nil), "atlas_validate.AtlasValidateFileOption")
	proto.RegisterType((*AtlasValidateMethodOption)(nil), "atlas_validate.AtlasValidateMethodOption")
	proto.RegisterType((*AtlasValidateServiceOption)(nil), "atlas_validate.AtlasValidateServiceOption")
	proto.RegisterType((*AtlasValidateFieldOption)(nil), "atlas_validate.AtlasValidateFieldOption")
	proto.RegisterEnum("atlas_validate.AtlasValidateFieldOption_Operation", AtlasValidateFieldOption_Operation_name, AtlasValidateFieldOption_Operation_value)
	proto.RegisterExtension(E_File)
	proto.RegisterExtension(E_Method)
	proto.RegisterExtension(E_Service)
	proto.RegisterExtension(E_Field)
}

func init() {
	proto.RegisterFile("github.com/infobloxopen/protoc-gen-atlas-validate/options/atlas_validate.proto", fileDescriptorAtlasValidate)
}

var fileDescriptorAtlasValidate = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0xff, 0xa4, 0xed, 0x54, 0xaa, 0xa2, 0x15, 0x12, 0xa6, 0xe2, 0x8f, 0x95, 0x0b,
	0x06, 0x29, 0x36, 0x0a, 0x37, 0x73, 0x2a, 0x48, 0xb9, 0xa0, 0xa6, 0x92, 0x11, 0x1c, 0xe0, 0x60,
	0xad, 0xd7, 0x63, 0x67, 0xc5, 0x76, 0xd7, 0xac, 0xd7, 0x2d, 0x3c, 0x09, 0x0f, 0xc8, 0x63, 0x70,
	0x41, 0x5d, 0xc7, 0x71, 0xdd, 0x40, 0x40, 0x3e, 0xd9, 0x9a, 0xf1, 0xf7, 0xfb, 0xc6, 0xfb, 0xcd,
	0xc2, 0xa2, 0xe0, 0x66, 0x59, 0xa7, 0x01, 0x53, 0x97, 0x21, 0x97, 0xb9, 0x4a, 0x85, 0xfa, 0xa6,
	0x4a, 0x94, 0x61, 0xa9, 0x95, 0x51, 0x6c, 0x5a, 0xa0, 0x9c, 0x52, 0x23, 0x68, 0x35, 0xbd, 0xa2,
	0x82, 0x67, 0xd4, 0x60, 0xa8, 0x4a, 0xc3, 0x95, 0xac, 0x42, 0x5b, 0x4e, 0xda, 0x72, 0x60, 0x05,
	0xe4, 0xa4, 0x5f, 0x3d, 0xf5, 0x0a, 0xa5, 0x0a, 0x81, 0x0d, 0x2e, 0xad, 0xf3, 0x30, 0xc3, 0x8a,
	0x69, 0x5e, 0x1a, 0xa5, 0x1b, 0xc5, 0xe4, 0x1d, 0x3c, 0x38, 0xbb, 0xd1, 0x7c, 0x5c, 0x49, 0xe6,
	0x5c, 0xe0, 0x85, 0xb5, 0x20, 0x2f, 0xe1, 0x3e, 0x15, 0x42, 0x5d, 0x27, 0xb5, 0xfc, 0x22, 0xd5,
	0xb5, 0x4c, 0x72, 0x8e, 0x22, 0xab, 0x5c, 0xc7, 0x73, 0xfc, 0xc3, 0x98, 0xd8, 0xde, 0x87, 0xa6,
	0x35, 0xb7, 0x9d, 0xc9, 0x39, 0x3c, 0xec, 0xc1, 0xce, 0xd1, 0x2c, 0x55, 0x36, 0x18, 0xb7, 0x80,
	0xd3, 0x1e, 0xee, 0x3d, 0xea, 0x2b, 0xce, 0x86, 0x8f, 0xf7, 0xd3, 0x01, 0xf7, 0xce, 0xcf, 0xa2,
	0x68, 0xc7, 0x9b, 0xc3, 0x5e, 0x86, 0xf2, 0xbb, 0xeb, 0x78, 0xbb, 0xfe, 0xc9, 0x6c, 0x16, 0xdc,
	0x39, 0xdf, 0xbf, 0xe9, 0x82, 0x8b, 0x12, 0x35, 0xbd, 0x79, 0x8b, 0xad, 0x9e, 0x2c, 0xe0, 0x50,
	0xe3, 0xd7, 0x9a, 0x6b, 0xcc, 0xdc, 0x9d, 0xc1, 0xac, 0x35, 0x63, 0x12, 0xc2, 0xd1, 0xba, 0x4c,
	0x00, 0x46, 0x4c, 0x23, 0x35, 0x38, 0xbe, 0x47, 0x8e, 0x60, 0xbf, 0xa4, 0x86, 0x2d, 0xc7, 0x0e,
	0x39, 0x86, 0x03, 0x8d, 0xa5, 0xa0, 0x0c, 0xc7, 0x3b, 0xd1, 0x67, 0xd8, 0xcb, 0xb9, 0x40, 0xf2,
	0x28, 0x68, 0xc2, 0x0f, 0xda, 0xf0, 0x83, 0x2e, 0xdb, 0xca, 0xfd, 0xf5, 0x63, 0xd7, 0x73, 0xfc,
	0xe3, 0xd9, 0xb3, 0x7f, 0x0c, 0xd7, 0x2a, 0x62, 0x0b, 0x8d, 0x18, 0x8c, 0x2e, 0x6d, 0xa8, 0xe4,
	0xc9, 0x06, 0xfe, 0x76, 0xda, 0x9d, 0xc1, 0xf3, 0xad, 0x06, 0xb7, 0x35, 0xf1, 0x0a, 0x1d, 0x15,
	0x70, 0x50, 0x35, 0x51, 0x93, 0xa7, 0x1b, 0x2e, 0xbd, 0x25, 0xe8, 0x6c, 0x5e, 0x6c, 0xb5, 0xe9,
	0x89, 0xe2, 0x96, 0x1e, 0x25, 0xb0, 0x6f, 0x97, 0x86, 0x3c, 0xfe, 0xc3, 0x59, 0xad, 0x63, 0xe9,
	0x4c, 0xfc, 0xff, 0x4d, 0x32, 0x6e, 0xb8, 0x6f, 0xde, 0x7e, 0x3a, 0x1b, 0x7c, 0xc3, 0x5f, 0xaf,
	0x9e, 0xe9, 0xc8, 0x7e, 0xfa, 0xea, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x07, 0x7a, 0x14,
	0x2d, 0x04, 0x00, 0x00,
}
